spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BookMarketPlaceDB
    username: ${'DB_USERNAME'}
    password : ${'DB_PASSWORD'}
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
